# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/mui-toolpad/v0.5.2/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  alias:
    - fyS83fh
  title: Tracklink - Login
  displayName: Login
  content:
    - component: Image
      name: image
      layout:
        horizontalAlign: center
      props:
        fit: contain
        loading: false
