services:
  
  tracklink-frontend-mbp:
    container_name: tracklink-frontend-mbp
    build: ./tracklink-frontend-mbp
    environment:
      CHOKIDAR_USEPOLLING: true # create-ui-app <= 5.x
      WATCHPACK_POLLING: true # create-ui-app >= 5.x
      FAST_REFRESH: false
      WDS_SOCKET_PORT: 3000 # The mapped port on your host machine
    ports:
      - "80:3000"
    volumes:
      - ./tracklink-frontend-mbp:/app
      - ./tracklink-frontend-mbp/node_modules:/app/node_modules
    networks:
      - backend_network

  fastapi:
    build: ./fastapi
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./app/media:/app/media  # Mount the media folder for persistent storage
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
      - MEDIA_ROOT=/app/media

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5430:5430"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

  media:
    image: nginx:latest
    container_name: media_server
    ports:
      - "8080:80"
    volumes:
      - ./fastapi/app/media:/usr/share/nginx/html:ro  # Serve media files through Nginx
    depends_on:
      - fastapi

networks:
  backend_network:
    driver: bridge

volumes:
  pgdata: