services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
      FAST_REFRESH: false
      WDS_SOCKET_PORT: 3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api
    restart: on-failure
    networks:
      - backend_network

  api:
    container_name: api
    build: ./api
    working_dir: /code/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5430/tracklink
    volumes:
      - ./api:/code/app
    depends_on:
      - database
    restart: on-failure
    networks:
      - backend_network

  database:
    container_name: database
    build: ./database
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tracklink
    volumes:
      - ./database/db-pgdata-gitignore:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  pgdata: